### ISSUE TITLE
gradients problem

### ISSUE THREAD

**Issue by CCH0124** [King-Of-Knights/overcoming-catastrophic#1]
The following error appears in the line "grads = K.gradients(K.log(model.output), model.weights)[m]".

`tf.gradients is not supported when eager execution is enabled. Use tf.GradientTape instead.`

**Comment by Zhongzheng-hl** [comment]
Me too. I used Tensorflow 2 and change this part as follow:
 
`    for j in range(num_sample):
        img_index = np.random.randint(imgset.shape[0])
        for m in range(len(model.weights)):
            with tf.GradientTape() as tape:
                output = model(np.expand_dims(imgset[img_index], 0))
                tape.watch(model.weights[m])
                gradients = tape.gradient(K.log(output), model.weights[m])
                f_accum[m] += np.square(gradients)
    f_accum /= num_sample`

Hope it is helpful.

**Comment by QiaoZhongzheng** [comment]
I also met this problem. I used Tensorflow2 and solve this problem by chaning that part as follows:
```

    for j in range(num_sample):
        img_index = np.random.randint(imgset.shape[0])
        for m in range(len(model.weights)):
            with tf.GradientTape() as tape:
                output = model(np.expand_dims(imgset[img_index], 0))
                tape.watch(model.weights[m])
                gradients = tape.gradient(K.log(output), model.weights[m])
                f_accum[m] += np.square(gradients)
    f_accum /= num_sample
```
Hope it is helpful.
